// This code was entirely generated by ChatGPT, I just copied it and changed some of the variable names.

// Includes
// General cpp libraries
#include <fstream>
#include <iostream>
#include <memory>
#include <filesystem>

// ROS2 specific libraries
#include "rclcpp/rclcpp.hpp"
#include "rclcpp/serialization.hpp"
#include "rosbag2_cpp/reader.hpp"
#include "rosbag2_storage/storage_options.hpp"
#include "rosbag2_cpp/converter_options.hpp"

// Messages
#include "sensor_msgs/msg/image.hpp"

// OpenCV
#include <opencv2/opencv.hpp>

int main (int argc, char ** argv) {

    // Check that the number of arguments is correct
    if (argc != 4) {
        std::cerr << "Expected 4x arguments: ros2 run tool left_camera_data_to_png <rosbag_path> <output_folder> <number_of_images>" << std::endl;
        return 1;
    }

    // Get rosbag path and CSV file path
    const std::string bag_path = argv[1];
    const std::string output_folder = argv[2];
    const int max_images = std::stoi(argv[3]);

    // Create output folder
    std::filesystem::create_directories(output_folder);

    // Open rosbag
    rosbag2_cpp::Reader reader;
    rosbag2_storage::StorageOptions storage_options;
    storage_options.uri = bag_path;
    storage_options.storage_id = "sqlite3";
    rosbag2_cpp::ConverterOptions converter_options;
    converter_options.input_serialization_format = "cdr";
    converter_options.output_serialization_format = "cdr";
    reader.open(storage_options, converter_options);

    // Serialization object
    rclcpp::Serialization<sensor_msgs::msg::Image> serialization;

    int image_count = 0;

    while (reader.has_next() && image_count < max_images) {
        auto bag_msg = reader.read_next();

        // Ignore all topics except "left_synchronized_images"
        if (bag_msg->topic_name != "/left_synchronized_images") {
            continue;
        }

        // Deserialize
        rclcpp::SerializedMessage serialized_msg(*bag_msg->serialized_data);
        sensor_msgs::msg::Image msg;

        serialization.deserialize_message(
            &serialized_msg,
            &msg);

        // Convert ROS image to OpenCV image
        cv::Mat bayer_image(
            msg.height,
            msg.width,
            CV_8UC1,
            msg.data.data(),
            msg.step
        );

        // Convert Bayer RGGB -> BGR
        cv::Mat image;
        cv::cvtColor(
            bayer_image,
            image,
            cv::COLOR_BayerRG2BGR
        );

        // Generate filename
        std::string filename = output_folder + "/image_" + std::to_string(image_count) + ".png";

        // Save image
        if (!cv::imwrite(filename, image)) {
            std::cerr << "Failed to save image number " << image_count << std::endl;
            continue;
        }

        // Increase counter
        image_count++;

    }

    // Notify of completion
    std::cout << "Finished extracting images" << "\n";

    return 0;

}