can_driver:
  ros__parameters:
    # Acceptable IMU rates:
    # 1. 26 Hz
    # 2. 52 Hz
    # 3. 104 Hz
    # 4. 208 Hz
    # 5. 416 Hz
    # 6. 833 Hz
    imu_rate: 208 # Hz
    camera_rate: 50 # FPS