can_driver:
  ros__parameters:
    # Acceptable IMU rates:
    # 1. 26 Hz
    # 2. 52 Hz
    # 3. 104 Hz
    # 4. 208 Hz
    # 5. 416 Hz
    # 6. 833 Hz
    imu_rate: 208 # Hz
    camera_rate: 50 # FPS

camera_driver:
  ros__parameters:
    autoexposure_time_lower_limit: 1000.0 # [us] <-- think about this more!!!  I just made something up
    autoexposure_time_upper_limit: 10000.0 # [us] <-- think about this more!!!  I just made something up