orchestrator:
  ros__parameters:
    camera_calibration_samples: 10 # at 50 FPS this is 5s of data

can_driver:
  ros__parameters:
    # Acceptable IMU rates:
    # 1. 26 Hz
    # 2. 52 Hz
    # 3. 104 Hz
    # 4. 208 Hz
    # 5. 416 Hz
    # 6. 833 Hz
    imu_rate: 416 # Hz
    camera_rate: 50 # FPS

camera_driver:
  ros__parameters:
    min_exposure_time: 3000.0 # [us] <-- think about this more!!!  I just made something up
    max_exposure_time: 5000.0 # [us] <-- think about this more!!!  I just made something up
