#ifndef ASM330LHH_H
#define ASM330LHH_h

// Include STM32 autogenerated code
#include "main.h"
#include "stdbool.h"

// Define addresses and registers
// DEN (Data Enable) Configuration: Level-sensitive latched mode
#define CTRL6_C_ADDR            0x15
#define CTRL6_C_DEN             0x60
#define CTRL6_C_STANDARD        0x00
#define CTRL9_XL_ADDR           0x18
#define CTRL9_XL_DEN            0x3A
#define CTRL9_XL_STANDARD       0x02
// DRDY (Data Ready) Configuration
#define INT1_CTRL_ADDR          0x0D
#define INT1_CTRL_DEN           0x80
#define INT1_CTRL_STANDARD      0x03
// FIFO Configuration
#define FIFO_CTRL4_ADDR         0x0A
#define FIFO_CTRL4              0x00
// Accelerometer configuration
#define CTRL1_XL_ADDR           0x10
#define CTRL1_XL_833            0x78 // 833 Hz, +/- 4 g, output from LPF1
#define CTRL1_XL_1667           0x88 // 1667 Hz, +/- 4 g, output from LPF1
#define CTRL1_XL_3333           0x98 // 3333 Hz, +/- 4 g, output from LPF1
#define CTRL1_XL_6667           0xA8 // 6667 Hz, +/- 4 g, output from LPF1
#define CTRL8_XL_ADDR           0x17
#define CTRL8_XL                0x00
// Gyroscope configuration
#define CTRL2_G_ADDR            0x11
#define CTRL2_G_833             0x74 // 833 Hz, +/- 500 dps
#define CTRL2_G_1667            0x84 // 1667 Hz, +/- 500 dps
#define CTRL2_G_3333            0x94 // 3333 Hz, +/- 500 dps
#define CTRL2_G_6667            0xA4 // 6667 Hz, +/- 500 dps
#define CTRL7_G_ADDR            0x16
#define CTRL7_G                 0x00
// Accelerometer Measurement Registers
#define OUTX_H_A_ADDR           0x29
#define OUTX_L_A_ADDR           0x28
#define OUTY_H_A_ADDR           0x2B
#define OUTY_L_A_ADDR           0x2A
#define OUTZ_H_A_ADDR           0x2D
#define OUTZ_L_A_ADDR           0x2C
// Gyroscope Measurement Registers
#define OUTX_H_G_ADDR           0x23
#define OUTX_L_G_ADDR           0x22
#define OUTY_H_G_ADDR           0x25
#define OUTY_L_G_ADDR           0x24
#define OUTZ_H_G_ADDR           0x27
#define OUTZ_L_G_ADDR           0x26
// Status Registers
#define STATUS_REG_ADDR         0x1E
#define STATUS_REG_MASK         0x03

// Define miscellaneous variables
#define BUFFER_SIZE 8
#define TIMEOUT 100
extern SPI_HandleTypeDef hspi2;

// Define variables private to asm330lhh.c
static uint8_t write_buffer[BUFFER_SIZE];
static uint8_t read_buffer[BUFFER_SIZE];
static uint8_t FIFO_CTRL3;
static uint8_t CTRL1_XL;
static uint8_t CTRL2_G;

// Define IMU error states
typedef enum {
	IMU_OK,
	ERROR_WRITING_CTRL6_C,
	ERROR_WRITING_CTRL9_XL,
	ERROR_WRITING_INT1_CTRL,
	ERROR_SETTING_FREQUENCY,
	ERROR_WRITING_FIFO_CTRL4,
	ERROR_WRITING_CTRL1_XL,
	ERROR_WRITING_CTRL8_XL,
	ERROR_WRITING_CTRL2_G,
	ERROR_WRITING_CTRL7_G,
	ERROR_CHECKING_FOR_MEASUREMENTS,
	ERROR_READING_X_ACCEL,
	ERROR_READING_Y_ACCEL,
	ERROR_READING_Z_ACCEL,
	ERROR_READING_X_GYRO,
	ERROR_READING_Y_GYRO,
	ERROR_READING_Z_GYRO,
	ERROR_CHECKING_IF_MEASUREMENTS_READY
} imu_state_t;

// Define SPI error states
typedef enum {
	IMU_SPI_OK,
	TRANSMITTING_W_ADDR,
	TRANSMITTING_R_ADDR,
	RECEIVING_BYTE,
	WRITTEN_BYTE_DOESNT_MATCH,
	DEN_STAMP_MISSING
} imu_spi_state_t;

// Structure to store general and SPI error states
typedef struct {
	imu_state_t state;
	imu_spi_state_t spi_state;
} imu_status_t;

// Define functions
imu_spi_state_t write_imu_byte(uint8_t address, uint8_t data);

imu_status_t configure_imu(int32_t frequency, bool den_enable);

imu_state_t set_imu_frequency(int32_t frequency);

imu_status_t check_if_imu_measurements_ready(bool *measurements_ready);

imu_spi_state_t read_single_imu_measurement(uint8_t address, int16_t *measurement, bool check_den_stamp);

imu_status_t read_imu_measurements(int16_t *x_accel, int16_t *y_accel, int16_t *z_accel,
								   int16_t *x_gyro, int16_t *y_gyro, int16_t *z_gyro,
								   bool den_enabled);

#endif
