#ifndef ASM330LHH_H
#define ASM330LHH_h

// Include STM32 autogenerated code
#include "main.h"

// Define addresses and registers
// DEN (Data Enable) Configuration: Edge-sensitive trigger mode
#define CTRL6_C_ADDR            0x15
#define CTRL6_C_DEN             0x80
#define CTRL9_XL_ADDR           0x18
#define CTRL9_XL_DEN            0x0A
// FIFO Configuration
#define FIFO_CTRL1_ADDR         0x07
#define FIFO_CTRL1              0x00
#define FIFO_CTRL2_ADDR         0x08
#define FIFO_CTRL2              0x00
#define FIFO_CTRL3_ADDR         0x09
#define FIFO_CTRL3_833          0x77 // 833 Hz
#define FIFO_CTRL3_1667         0x88 // 1667 Hz
#define FIFO_CTRL3_3333         0x99 // 3333 Hz
#define FIFO_CTRL3_6667         0xAA // 6667 Hz
#define FIFO_CTRL4_ADDR         0x0A
#define FIFO_CTRL4              0x06
// Accelerometer configuration
#define CTRL1_XL_ADDR           0x10
#define CTRL1_XL_833            0x78 // 833 Hz, +/- 4 g, output from LPF1
#define CTRL1_XL_1667           0x88 // 1667 Hz, +/- 4 g, output from LPF1
#define CTRL1_XL_3333           0x98 // 3333 Hz, +/- 4 g, output from LPF1
#define CTRL1_XL_6667           0xA8 // 6667 Hz, +/- 4 g, output from LPF1
#define CTRL8_XL_ADDR           0x17
#define CTRL8_XL                0x00
// Gyroscope configuration
#define CTRL2_G_ADDR            0x11
#define CTRL2_G_833             0x74 // 833 Hz, +/- 500 dps
#define CTRL2_G_1667            0x84 // 1667 Hz, +/- 500 dps
#define CTRL2_G_3333            0x94 // 3333 Hz, +/- 500 dps
#define CTRL2_G_6667            0xA4 // 6667 Hz, +/- 500 dps
#define CTRL7_G_ADDR            0x16
#define CTRL7_G                 0x00

// Define variables
#define BUFFER_SIZE 8
#define TIMEOUT 100

// Define functions
int write_byte(uint8_t address, uint8_t data);

int configure_den();

int set_frequency(int32_t frequency);

int configure_fifo();

int configure_accel();

int configure_gyro();

int read_from_registers();

int read_from_fifo();

int check_imu_alive();

#endif