#ifndef ASM330LHH_H
#define ASM330LHH_h

// Include STM32 autogenerated code
#include "main.h"

// Define addresses and registers
// DEN (Data Enable) Configuration: Level-sensitive latched mode
#define CTRL6_C_ADDR            0x15
#define CTRL6_C_DEN             0x60
#define CTRL6_C_STANDARD        0x00
#define CTRL9_XL_ADDR           0x18
#define CTRL9_XL_DEN            0x3A
#define CTRL9_XL_STANDARD       0x02
// DRDY (Data Ready) Configuration
#define INT1_CTRL_ADDR          0x0D
#define INT1_CTRL_DEN           0x80
#define INT1_CTRL_STANDARD      0x03
// FIFO Configuration
#define FIFO_CTRL4_ADDR         0x0A
#define FIFO_CTRL4              0x00
// Accelerometer configuration
#define CTRL1_XL_ADDR           0x10
#define CTRL1_XL_833            0x78 // 833 Hz, +/- 4 g, output from LPF1
#define CTRL1_XL_1667           0x88 // 1667 Hz, +/- 4 g, output from LPF1
#define CTRL1_XL_3333           0x98 // 3333 Hz, +/- 4 g, output from LPF1
#define CTRL1_XL_6667           0xA8 // 6667 Hz, +/- 4 g, output from LPF1
#define CTRL8_XL_ADDR           0x17
#define CTRL8_XL                0x00
// Gyroscope configuration
#define CTRL2_G_ADDR            0x11
#define CTRL2_G_833             0x74 // 833 Hz, +/- 500 dps
#define CTRL2_G_1667            0x84 // 1667 Hz, +/- 500 dps
#define CTRL2_G_3333            0x94 // 3333 Hz, +/- 500 dps
#define CTRL2_G_6667            0xA4 // 6667 Hz, +/- 500 dps
#define CTRL7_G_ADDR            0x16
#define CTRL7_G                 0x00
// Accelerometer Measurement Registers
#define OUTX_H_A_ADDR           0x29
#define OUTX_L_A_ADDR           0x28
#define OUTY_H_A_ADDR           0x2B
#define OUTY_L_A_ADDR           0x2A
#define OUTZ_H_A_ADDR           0x2D
#define OUTZ_L_A_ADDR           0x2C
// Gyroscope Measurement Registers
#define OUTX_H_G_ADDR           0x23
#define OUTX_L_G_ADDR           0x22
#define OUTY_H_G_ADDR           0x25
#define OUTY_L_G_ADDR           0x24
#define OUTZ_H_G_ADDR           0x27
#define OUTZ_L_G_ADDR           0x26

// Define variables
#define BUFFER_SIZE 8
#define TIMEOUT 100

// Define functions
int write_byte(uint8_t address, uint8_t data);

int configure_imu_den();

int configure_imu_standard();

int set_frequency(int32_t frequency);

int disable_fifo();

int configure_accel();

int configure_gyro();

int read_single_measurement(uint8_t address, int32_t *measurement, bool check_den_stamp);

int check_if_measurements_ready(bool *measurements_ready);

int read_measurements(int16_t *x_accel, int16_t *y_accel, int16_t *z_accel,
                      int16_t *x_gyro, int16_t *y_gyro, int16_t *z_gyro,
                      bool den_enabled);

#endif